--Incercati sa va definiti o noua baza de date care sa se numeasca CINEMA si care sa contina toate tabelel necesare pentru a modela o baza de date de tip cinema. 
-- Ganditi-va la ce tabele sa contina, ce coloane sa contina fiecare tabela, ce tipuri de date sa contina fiecare coloana si care sa fie relatia intre tabelele respective
	- creare baza de date
    - creare tabele (cu cheie primara si cheie secundara)
    - inserare de informatii
    - efectuarea diverselor tipuri de interogari pe tabele create anterior (inclusiv joinuri)